# create user

- hosts: monit
  become: yes
  vars_files:
          - ~/vars/defaults.yml
  tasks:
          - name: create a new user name "dimas"
            ansible.builtin.user:
                    name: dimas
                    password: "{{PASS}}"
                    shell: "{{BASH}}"
                    groups: sudo,docker
                    state: present
                    createhome: yes
                    home: "{{HOME}}"
                    generate_ssh_keys: yes
                    ssh_key_bits: 4096
                    ssh_key_file: "{{PRIVATE}}"
                    ssh_public_key: "{{PUBLIC}}"

# allow ssh login

- hosts: monit
  become: yes
  tasks:
          - name: change password authentication
            ansible.builtin.replace:
                    path: /etc/ssh/sshd_config
                    regexp: "PasswordAuthentication no"
                    replace: PasswordAuthentication yes
             
          - name: restart sshd service
            ansible.builtin.service:
                    name: sshd
                    state: restarted 

