# create user

- hosts: monit
  become: yes
  vars_files:
          - ~/vars/defaults.yaml
  tasks:
          - name: create a new user name "dimas"
            user:
                    name: dimas
                    password: "de5ce7308cfa92e9a31fec5fbb24a184de22baa89631f79f7d73ed48f07a1dcfd630f81950384cdad0c4ec09deb9b134b22180cc4ca392bb218699f17ad2aa1b"
                    shell: /bin/bash
                    groups: sudo
                    state: present
                    createhome: yes
                    #generate_ssh_keys: yes
                    #ssh_key_bits: 4096
                    #ssh_key_file: .ssh/id_rsa
                    #ssh_public_key: .ssh/id_rsa.pub

# allow ssh login

- hosts: monit
  become: yes
  tasks:
          - name: change password authentication
            lineinfile:
                    path: /etc/ssh/sshd_config
                    regexp: "PasswordAuthentication no"
                    line: PasswordAuthentication yes
             
          - name: restart sshd service
            service:
                    name: sshd
                    state: restarted 

