# create user

- hosts: monit
  become: yes
  vars_files:
          - ~/vars/defaults.yaml
  tasks:
          - name: create a new user name "dimas"
            user:
                    name: dimas
                    password: "$6$TwLAGHfdSsMfqLYQ$xtfAyXx6ElT70mRFLeiX.NEdGrPkHdCJgywDFH40tsJJUTUh2W4WOTyKMLNEx/prxnqqnfVAAatFu8RCqwDli."
                    shell: /bin/bash
                    groups: sudo
                    state: present
                    createhome: yes
                    #generate_ssh_keys: yes
                    #ssh_key_bits: 4096
                    #ssh_key_file: .ssh/id_rsa
                    #ssh_public_key: .ssh/id_rsa.pub

# allow ssh login

- hosts: monit
  become: yes
  tasks:
          - name: change password authentication
            lineinfile:
                    path: /etc/ssh/sshd_config
                    regexp: "PasswordAuthentication no"
                    line: PasswordAuthentication yes
             
          - name: restart sshd service
            service:
                    name: sshd
                    state: restarted 

