- hosts: frontend
  become: true
  vars_files:
      - ~/vars/defaults.yml
  tasks:
    - name: clone repo frontend
      git:
        repo: "{{ repo_frontend }}"
        dest: ~/waysgallery-frontend
    
    - name: delete directory repo
      file:
        path: ~/waysgallery-frontend
        state: absent
 
    - name: delete container
      shell: docker stop frontend && docker rm frontend

    - name: login into dockerhub
      docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
        email: "{{ docker_email }}"

    - name: Build an image and push it to a private repo
      docker_image:
        path: ~/waysgallery-frontend
        name: docker.io/dimasadriansah4/waysgallery-frontend
        tag: v1.3.0
        push: yes

    - name: copy docker-compose.yml to running dir
      copy:
        src: ./conf/systemd/frontend/docker-compose.yml
        dest: /var/docker-compose/docker-compose.yml

    - name: restart service docker-compose
      service:
        name: docker-compose
        state: restarted