- hosts: private-database-2
  become: true
  tasks:
          - name: create directory postgress
            file:
                    path: ~/postgresql
                    state: directory
                    mode: 0755

          - name: copy docker-compose.yml to running dir
            copy:
                    src: ./config/systemd/database-slave/docker-compose.yml
                    dest: /var/docker-compose/docker-compose.yml
          
          - name: restart service docker-compose
            service:
                    name: docker-compose
                    state: restarted