- hosts: private-database-2
  become: true
  tasks:
          - name: create directory postgress
            file:
                    path: ~/postgresql
                    state: directory
                    mode: 0755

          - name: copy docker-compose.yml to running dir
            copy:
                    src: ./conf/systemd/database-slave/docker-compose.yml
                    dest: /var/docker-compose/docker-compose.yml
          
          - name: copy my-postgres.conf
            copy:
                    src: ./conf/systemd/database-slave/my-postgres.conf
                    dest: /var/docker-compose/my-postgres.conf

          - name: copy pg_hba.conf
            copy:
                    src: ./conf/systemd/database-slave/pg_hba.conf
                    dest: /var/docker-compose/pg_hba.conf

          - name: restart service docker-compose
            service:
                    name: docker-compose
                    state: restarted