- hosts: monit 
  become: true
  tasks:
          - name: copy docker-compose.yml to running dir
            copy:
                    src: ./config/systemd/monitoring/docker-compose.yml
                    dest: /var/docker-compose/docker-compose.yml

          - name: create directory prometheus
            file:
                    path: ~/prometheus
                    state: directory
                    mode: 0755

          - name: prometheus file
            copy:
                    src: ./config/systemd/monitoring/prometheus.yml
                    dest: ~/prometheus/prometheus.yml

          - name: restart service docker-compose
            service:
                    name: docker-compose
                    state: restarted

          #- name: grafana file
           # copy:
            #        src: ./config/systemd/monitoring/grafana.ini
             #       dest: /home/ubuntu/grafana/grafana.ini
