- hosts: monit
  become: yes
  tasks:

      - name: create directory for portainer data 
        file:
            path: ~/portainer_data
            state: directory

      - name: run portainer
        shell: docker run -d -p 8000:8000 -p 9000:9000 --name=portainer -v /var/run/docker.sock:/var/run/docker.sock -v ~/portainer_data:/data portainer/portainer-ce