# install docker
- hosts: frontend
  become: true
  tasks:
        - name: install apttitude & update 
          apt: 
               name: aptitude 
               state: latest 
               update_cache: yes 
               force_apt_get: yes

        - name: install required system packages
          apt:
               pkg:
                      - apt-transport-https
                      - ca-certificates
                      - curl
                      - gnupg
                      - lsb-release
                      - python3-pip
                      - virtualenv
                      - software-properties-common

        - name: add docker GPG apt key
          apt_key:
               url: https://download.docker.com/linux/ubuntu/gpg
               state: present

        - name: Add docker repository
          apt_repository:
                repo: deb https://download.docker.com/linux/ubuntu bionic stable
                state: present

        - name: update apt and install docker
          apt: 
                name: docker-ce
                state: latest
                update_cache: yes

        - name: install docker cli
          apt:
                name: docker-ce-cli
                state: latest

        - name: install containerd
          apt:
               name: containerd.io
               state: latest

        - name: install pip
          apt:
               name: python-pip
               update-cache: yes
               state: latest

        - name: docker python
          pip:
               name: docker
               state: latest
# install docker-compose
        - name: install docker-compose
          get_url:
                url: "https://github.com/docker/compose/releases/download/1.29.1/docker-compose-Linux-x86_64"
                dest: /usr/local/bin/docker-compose
                mode: 0755

        - name: copy docker-compose systemd.service
          copy:
                src: ./conf/systemd/docker-compose.service
                dest: /etc/systemd/system/docker-compose.service

# create docker-compose dir running
        - name: Create direktori docker-compose file in /var
          file:
                path: /var/docker-compose
                state: directory
                mode: 0755

# enable service docker-compose
        - name: enable service docker-compose
          service:
               name: docker-compose
               enabled: yes
               state: started