global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'frontend'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.31.85.26:9100','172.31.95.166:9100']

  - job_name: 'backend'
    scrape_interval: 5s
    static_configs: 
      - targets: ['172.31.94.190:9100']

  - job_name: 'database'
    scrape_interval: 5s
    static_configs: 
      - targets: ['172.31.90.215:9100']

  - job_name: 'jenkins'
    scrape_interval: 5s
    static_configs: 
      - targets: ['172.31.89.217:9100']

  - job_name: 'ansible'
    scrape_interval: 5s
    static_configs: 
      - targets: ['172.31.90.133:9100']

  - job_name: 'nginx'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.31.41.152:9100']

