version: '3.9'
services: 
    nginx:
        container_name: nginx
        image: nginx/nginx:1.19-alpine
        ports: 
            - 80:80
            - 443:443
        volumes: 
            - /var/docker-compose/nginx.conf:/etc/nginx/nginx.conf
            - /var/docker-compese/waysgallery:/etc/nginx/waysgallery
            - /etc/letsencrypt:/etc/letsencrypt