version: '3.9'
services:
    postgres:
        container_name: postgres-slave
        image: postgres
        environment:
            - POSTGRESQL_REPLICATION_MODE=slave
            - POSTGRESQL_REPLICATION_USERNAME=master_repl
            - POSTGRESQL_REPLICATION_PASSWORD=master_repl123
            - POSTGRESQL_MASTER_HOST=172.31.90.215
            - POSTGRESQL_MASTER_PORT_NUMBER=5432
            - POSTGRESQL_USERNAME=dimas
            - POSTGRESQL_PASSWORD=dimas
            - NODE_ENV=production
            - POSTGRESQL_DATABASE=waysgallery
            - DATABASE_URL=postgres://dimas:dimas@172.31.90.215:5432/waysgallery
        ports:
            - 5432:5432
        volumes:
            - ~/postgresql:/var/lib/postgresql/data