version: '3.9'
services:
    postgres:
        container_name: postgres-slave
        image: postgres
        environment:
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=postgres
            - NODE_ENV=production
            - POSTGRES_DB=waysgallery
            - DATABASE_URL=postgres://dimas:dimas@172.31.90.215:5432/waysgallery
        ports:
            - 5432:5432
        volumes:
            - ~/data:/var/lib/postgresql/data