version: '3.9'
services:
    postgres:
        container_name: postgres-slave
        image: postgres
        environment:
            - POSTGRES_MASTER_HOST=172.31.90.215
            - POSTGRES_MASTER_PORT_NUMBER=5432
            - POSTGRES_USER=replicator
            - POSTGRES_PASSWORD=replicator123
            - NODE_ENV=production
            - POSTGRES_DB=waysgallery
            - DATABASE_URL=postgres://dimas:dimas@172.31.90.215:5432/waysgallery
        ports:
            - 5432:5432
        volumes:
            - ~/data-slave:/var/lib/postgresql/data
            - ./my-postgres.conf:/etc/postgresql/my-postgres.conf
            - ./pg_hba.conf:/etc/postgresql/pg_hba.conf