version: '3.9'
services:
    prometheus:
        image: prom/prometheus
        ports:
            - 9090:9090
        container_name: prometheus
        volumes:
            - /home/ubuntu/prometheus:/etc/prometheus
    grafana:
        image: grafana/grafana
        ports:
            - 3000:3000
        container_name: grafana

