global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'frontend'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.31.51.25:9100']

  - job_name: 'backend'
    scrape_interval: 5s
    static_configs: 
      - targets: ['172.31.36.8:9100','172.31.39.210:9100']

  - job_name: 'mysql'
    scrape_interval: 5s
    static_configs: 
      - targets: ['172.31.62.12:9100']

  - job_name: 'jenkins'
    scrape_interval: 5s
    static_configs: 
      - targets: ['172.31.48.70:9100']

  - job_name: 'ansible'
    scrape_interval: 5s
    static_configs: 
      - targets: ['172.31.57.12:9100']

