version: '3.9'
services: 
    postgres:
        container_name: postgres
        image: postgres
        environment:
            - POSGRES_PASSWORD="1234"
            - DATABASE_URL="postgres://postgres:postgres@172.31.90.215:5432/waysgallery"
        ports: 
            - "5432:5432"
        volumes: 
            - ~/postgresql:/var/lib/postgresql/data
