version: '3.9'
services: 
    backend:
        container_name: backend-1
        image: docker.io/dimasadriansah4/waysgallery-backend:v1.6.0
        ports: 
            - 5000:5000
        environment:
            - DATABASE_URL=postgres://dimas:dimas@172.31.90.215:5432/waysgallery
            - NODE_ENV=production
