version: '3.9'
services: 
    backend:
        container_name: backend-1
        image: docker.io/dimasadriansah4/waysgallery-backend:v1.0.0
        stdin_open: true
        ports: 
            - 5000:5000
